export enum EContentGroupQueries {
  FETCH_GROUPS = 'FETCH_GROUPS',
  FETCH_POSTS = 'FETCH_POSTS',
  FETCH_MEETUPS = 'FETCH_MEETUPS',
  FETCH_PODCASTS = 'FETCH_PODCASTS',
  FETCH_MEMBERS = 'FETCH_MEMBERS',
}
