export enum EUserContentGroupQueries {
  FETCH_USER_POSTS = 'FETCH_USER_POSTS',
  FETCH_USER_MEETUPS = 'FETCH_USER_MEETUPS',
  FETCH_USER_PODCASTS = 'FETCH_USER_PODCASTS',
  FETCH_USER_GROUPS = 'FETCH_USER_GROUPS',
}

export enum EAllContentGroupQueries {
  FETCH_ALL_GROUPS = 'FETCH_ALL_GROUPS',
  FETCH_ALL_POSTS = 'FETCH_ALL_POSTS',
  FETCH_ALL_MEETUPS = 'FETCH_ALL_MEETUPS',
  FETCH_ALL_PODCASTS = 'FETCH_ALL_PODCASTS',
}
