export enum EContentGroupQueries {
  FETCH_GROUPS = 'FETCH_GROUPS',
  FETCH_POSTS = 'FETCH_POSTS',
  FETCH_MEETUPS = 'FETCH_MEETUPS',
  FETCH_PODCASTS = 'FETCH_PODCASTS',
  FETCH_MEMBERS = 'FETCH_MEMBERS',
  FETCH_GROUPS_AND_CONTENTS = 'FETCH_GROUPS_AND_CONTENTS',
  DELETE_MEMBER = 'DELETE_MEMBER',
  ASSIGN_ADMIN_ROLE = 'ASSIGN_ADMIN_ROLE',
  REMOVE_ADMIN_ROLE = 'REMOVE_MEMBER_ROLE',
}
