import { ClerkProvider } from '@clerk/nextjs';
import ThemeProvider from '../context/ThemeProvider';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';

import { IBM_Plex_Sans } from 'next/font/google';

import QueryProvider from '@/context/QueryProvider';

import './globals.css';

// ----------------------------------------------------------------

const ibmPlexSans = IBM_Plex_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${ibmPlexSans.className} min-h-screen overflow-auto bg-white-200 dark:bg-black-900`}
          >
            <ThemeProvider>
              <main className="mx-auto max-w-screen-xxl">{children}</main>
              <ReactQueryDevtools />
            </ThemeProvider>
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
};

export default RootLayout;
